### PR TITLE
Rewrite srcset links,  Fix #1939

### LINKED ISSUE #1939: srcset not respecting URL_TYPE option
1. Set `URL_TYPE = 'rel_path'` (default)
2. Make a post with ``

Expected:
``

Actual:
``

### PR DESCRIPTION
**Pull request by ralsina**

### CODE REVIEW

**Comment by ralsina** [comment]
@Aeyoun review much appreciated :-)

**Comment by Aeyoun** [comment]
Seems only the first link in the srcset is rewritten.

This input:
    srcset="/images/xbox_logo_128.webp 128w,  /images/xbox_logo_256.webp 256w,  /images/xbox_logo_512.webp 512w,  /images/xbox_logo_1024.webp 1024w"

Produced this output:
    srcset="../images/xbox_logo_128.webp 128w,  /images/xbox_logo_256.webp 256w,  /images/xbox_logo_512.webp 512w,  /images/xbox_logo_1024.webp 1024w"

**Comment by ralsina** [comment]
@Aeyoun weird.... I'll take another look then.

**Comment by ralsina** [comment]
@Aeyoun leading spaces did weird things. Should work better now.

**Comment by Aeyoun** [comment]
Looks good. :+1:

 Took a while to verify as I’d messed up the formatting of this almost everywhere in my site. Kept blaming the code but every instance was me throwing very broken markup at it.

**Pull request merged**
