### PR TITLE
generic_rss_renderer refactor

### PR DESCRIPTION
**Pull request by anderbubble**
### Pull Request Checklist

- [X] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [X] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [X] I tested my changes.

### Description

I split actual feed generation into `generic_rss_feed` and writing into `utils.rss_writer`, both of which are now called from the (much smaller) `generic_rss_renderer`. This allows plugins to use `generic_rss_feed`, modify the resultant feed, and then write it out with `utils.rss_writer`.

In my use case, I'm building a "postcast" plugin to generate podcasts from posts. I want to add iTunes-specific tags to the podcast RSS feeds, but I didn't like the feeling of bolting domain-specific tags into the central rss renderer. My WIP plugin can now use the upstream code, but modify the result before it's written out to a file.

I've further made a small change to `ExtendedItem` to make it easier to subclass, as I use subclasses of `ExtendedRSS2` and `ExtendedItem` to actually apply the iTunes tags.

### CODE REVIEW

**Comment by anderbubble** [comment]
I'll add some docstrings later. Let me know if this kind of internal change justifies an entry in `CHANGES.txt`.

**Comment by ralsina** [comment]
Sure, you can put in CHANGES something like:

* Refactoring allowing plugins better access to feed generation

Also, remember to add yourself to authors if you are not there.

**Comment by anderbubble** [comment]
OK. I've added docstrings and updated CHANGES.

As an aside, I'd love for someone to look over the related plugin work I'm doing, too; but I don't know that a PR is the best place for it. Any advice?

**Comment by felixfontein** [comment]
Is your current plugin code available somewhere on github?

**Comment by anderbubble** [comment]
@felixfontein not yet, but I just found the appropriate documentation[1], so I'll do that soon.

[1]: https://github.com/getnikola/plugins/blob/master/README.md

**Comment by felixfontein** [comment]
You can also create a new repository in your own github account and put it there; but forking and creating a PR for getnikola/plugins is of course fine, too.

**Comment by anderbubble** [comment]
@felixfontein It's not done, but here's what I'm ultimately working on: https://github.com/anderbubble/nikola-postcast

**Comment by felixfontein** [comment]
Both PR and your plugin look fine to me.

(In the plugin, you seem to ignore the `SHOW_UNTRANSLATED_POSTS` setting and you might also want to check `post.is_post` before including it into the feed to exclude pages.)

**Comment by anderbubble** [comment]
@felixfontein thanks for the comments. I've created anderbubble/nikola-postcast#5 and anderbubble/nikola-postcast#6 to track your suggestions.

**Comment by felixfontein** [comment]
Apropos: do you want to leave this PR open a bit more, or do you want to see it merged soon?

**Comment by anderbubble** [comment]
Up to you. I'm running out of a fork that has it merged already. ;) But if
it were merged upstream, one less divergence for me.

Biggest problem with it, I suspect, is that it doesn't update the atom
generator in kind. But I'm not using it, either, so I wouldn't have a
built-in test case, either.

**Comment by Kwpolska** [comment]
Merged because it can be useful for others, and Atom works completely differently anyway.

**Pull request merged**
