### PR TITLE
added Punjabi translations

### PR DESCRIPTION
**Pull request by jasdeep**

### CODE REVIEW

**Comment by Kwpolska** [comment]
Use Transifex. Also, please try to create 'pa' instead of 'pa_in', please undo your current request.



-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by jasdeep** [comment]
I have requested both 'pa' and pa_in'  at transifex, but none has been accepted yet.

**Comment by Kwpolska** [comment]
pa is now in transifex

**Comment by jasdeep** [comment]
Thanks, I have added the translations there. Do I need to make changes in code and documentation somewhere as well?

**Comment by Kwpolska** [comment]
We have to handle that. Done in 1bcf996.

**Comment by jasdeep** [comment]
Thanks much

**Pull request closed without merging**
