### PR TITLE
improved Docs 

### PR DESCRIPTION
**Pull request by shiven111**
### Pull Request Checklist

- [ ] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [ ] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [ ] I tested my changes.

### CODE REVIEW

**Comment by Kwpolska** [comment]
1. Adjectives in English are not capitalized in the middle of a sentence.
2. This is an internal file that nobody sees.
3. Spam pull requests like this one might get you a Hacktoberfest t-shirt, but are against the spirit of open source and a burden for maintainers. You can try again with a more appropriate PR. (This one will be marked as invalid and will not count towards Hacktoberfest. Future abuse can lead to a block.)

**Comment by shiven111** [comment]
Sorry dude if you r hurt but i was new to github that's why I pulled
request which was also not up to mark. I apologize to you I thought you
will not accept but you will also not reject. Again sorry i will keep what
you told me about not doing this.

**Comment by Kwpolska** [comment]
If you’re new to a project, consider looking through their issues first and fixing issues provided there. I checked your profile and most changes you made to other projects are random one-line changes to docs or other minor areas. This is not a good way to contribute to open source software. While improving docs is definitely encouraged and definitely a good way to contribute, contributions should be bigger than changing a single line in the docs, or making an unimportant variable rename. Think of the project maintainers that now have to react to PRs like these, and consider if you should add work for those volunteers just so you get a t-shirt.

We welcome future contributions from you, and from everyone else — in code or docs, big or small — but please make sure your contribution actually helps the projects you’re contributing to.

**Comment by shiven111** [comment]
Thankyou for encouraging me.. I will keep your suggestion in mind and will
work toward it.

**Pull request closed without merging**
