### PR TITLE
fix unicode arguments

### PR DESCRIPTION
**Pull request by Kwpolska**
this is a73ed63590e75fd9cb87baac93bd652f11a70594

cc @felixfontein

### CODE REVIEW

**Comment by felixfontein** [comment]
When running `nikola build` with this branch under Python 3, I get:
```
Traceback (most recent call last):
  File "/usr/bin/nikola", line 9, in <module>
    load_entry_point('Nikola==7.4.1', 'console_scripts', 'nikola')()
  File "~/nikola/nikola/__main__.py", line 108, in main
    root = get_root_dir()
  File "~/nikola/nikola/utils.py", line 1152, in get_root_dir
    if os.path.exists(os.path.join(root, b'conf.py')):
  File "/usr/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by Kwpolska** [comment]
So that needs a bloody `if`/`else`.  Will do tomorrow.

**Comment by felixfontein** [comment]
Changing line 1152 in `utils.py` to
```
        if os.path.exists(os.path.join(root, 'conf.py')):
```
fixes it for me.

**Comment by felixfontein** [comment]
Ok. Thank you very much :)

**Comment by Kwpolska** [comment]
does 5c59b19 fix it for you?

**Comment by felixfontein** [comment]
No. `confname` is still `b'conf.py'`, which makes it fail.

**Comment by Kwpolska** [comment]
should be good now

**Comment by felixfontein** [comment]
Yes, works for me now. Thanks! :)

**Comment by Kwpolska** [comment]
@ralsina, mind reviewing and merging?

**Pull request merged**
