### PR TITLE
Don't create download directories when not downloading uploads.

### LINKED ISSUE #2260: import_wordpress --no-downloads still creates empty folders
```
[2016-02-23T15:43:03Z] INFO: init: Created empty site at new_site.
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/dashboard.jpg => new_site/files/blog/wp-content/uploads/2007/05/dashboard.jpg
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/screenshot7.jpeg => new_site/files/blog/wp-content/uploads/2007/05/screenshot7.jpeg
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012766.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012766.JPG
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012763.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012763.JPG
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png
[2016-02-23T15:43:03Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png
```

```
new_site/files/blog/
└── wp-content
    └── uploads
        ├── 2007
        │   ├── 05
        │   └── 07
        └── 2010
            └── 12
```

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #2260.

### CODE REVIEW

**Comment by Kwpolska** [comment]
One more: https://github.com/getnikola/nikola/blob/dont-create-folders-when-download-disabled/nikola/plugins/command/import_wordpress.py#L573

**Comment by Kwpolska** [comment]
I’ll fix this and merge.

**Comment by felixfontein** [comment]
Ok. I just wanted to continue on this, but feel free to finish it instead :)

**Comment by Kwpolska** [comment]
Done in 87286f1, does that look good to you?

**Comment by felixfontein** [comment]
Yes, looks good!

**Pull request merged**
