### PR TITLE
change wording in teaser comments

### PR DESCRIPTION
**Pull request by Wayneoween**
I was confused that this setting may change some other stuff too.
imho this describes the effect better.

### CODE REVIEW

**Comment by Kwpolska** [comment]
I'm not sure about this... "Show only teasers" makes sense IMO, where "Activate" is vague.

**Comment by Wayneoween** [comment]
Ok, it was just a thought anyways and English is not my first language, so there may be that.

"Show only" sounds to me like it excludes teasers from somewhere else. Maybe "Use teasers" is better?

**Comment by ralsina** [comment]
I agree with @Kwpolska ... if any native english speakers see this and can comment, much appreciated :-)

**Comment by Kwpolska** [comment]
I believe we should phrase it like this:




# Show teasers (instead of full posts) in indexes/feeds? Defaults to False.




This makes it more clear, and also fixes awkward syntax (“Show only”).




PS. I actually have a very fancy certificate that proves I speak English on a near-native level (CEFR C2).





-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
@Kwpolska hey, one of my favourite english writers was a pole :)

**Comment by Kwpolska** [comment]
Who is it?


Also, would you mind implementing the revised description above?





-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
@Kwpolska Jseph Conrad! Done.

**Pull request closed without merging**
