### PR TITLE
Remove incorrect attempt to change ipynb template

### PR DESCRIPTION
**Pull request by punchagan**
The previous code intended to set the template to basic, but it doesn't
really work and the full template was being used.

### CODE REVIEW

**Comment by punchagan** [comment]
@damianavila Does this change look OK to you? It works fine for me.

**Comment by damianavila** [comment]
As long as we are not breaking the `status quo`, I am OK.
Originally the idea was to use the basic template so anyone can do their own stuff... BUT...
Which is the default experience if we turn this to actually use the basic template?
I don't want to break the current user experience in the default setup...

**Comment by punchagan** [comment]
@damianavila Fair enough.  I just removed the confusing line which attempts to change the template, but doesn't work. 

Users can use `IPYNB_CONFIG` if they really want the basic template.

**Comment by Kwpolska** [comment]
Let’s merge this if the original was broken.

**Comment by punchagan** [comment]
Just to clarify, the PR now just removes the code which tries to change the template to basic, but doesn't work correctly.  The full template will be used, and users can switch to basic template using the `IPYNB_CONFIG` setting.

**Comment by damianavila** [comment]
Yep, understood... I agree with the merge. Thanks @punchagan

**Pull request merged**
