### PR TITLE
Fix #1954 Cause RuntimeError if plugin throw StopIteration

### LINKED ISSUE #1954: raise StopIteration in read_metadata() method make false report
I found strange behavior if I add `raise StopIteration` in `read_metadata()` method in plugin class whitch inherit PageCompiler class.
I execute `NIKOLA_DEBUG=True nikola build -a`, I got:
```
...(snip)...
[2015-08-19T18:37:31Z] DEBUG: yapsy: README.md is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: conf.py.sample is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: init.el is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: macros.org is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: PluginFileLocator found a candidate:
    /home/kaoru/Writing/blog/plugins/orgmode/orgmode.plugin
[2015-08-19T18:37:31Z] DEBUG: yapsy: requirements-nonpy.txt is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: orgmode.py is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: orgmode.pyc is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: orgmode.cpython-34.pyc is not a valid plugin for strategy info_ext
[2015-08-19T18:37:31Z] DEBUG: yapsy: PluginFileLocator skips /home/kaoru/.nikola/plugins (not a directory)
[2015-08-19T18:37:31Z] WARNING: ShimWarning: /home/kaoru/Environment/Nikola-py2/lib/python2.7/site-packages/IPython/nbconvert.py:13: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
[2015-08-19T18:37:31Z] WARNING: ShimWarning: /home/kaoru/Environment/Nikola-py2/lib/python2.7/site-packages/IPython/nbformat.py:13: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
[2015-08-19T18:37:31Z] WARNING: ShimWarning: /home/kaoru/Environment/Nikola-py2/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
[2015-08-19T18:37:31Z] WARNING: ShimWarning: /home/kaoru/Environment/Nikola-py2/lib/python2.7/site-packages/IPython/config.py:13: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...ERROR: render_site. Task dependency 'generate_rss' does not exist.
```
I think Nikola plugin mechanism should catch this exception as other exceptions.

### PR DESCRIPTION
**Pull request by pluser**
Make Nikola raise RuntimeError If plugin throw StopIteration exception.
See the #1954 for detail.

### CODE REVIEW

**Comment by Kwpolska** [comment]
Why bother? I would call this *user error* and *not even following basic APIs because the function must return dicts*

:-1:

**Comment by pluser** [comment]
Yes. That is user error. Of course, user should return dicts.
However, If user mistake and raise exception, It is better to show kind error message (like Traceback) instead of ambiguous message like: `Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...Scanning posts...ERROR: render_site. Task dependency 'generate_rss' does not exist.`.
Would you agree with this view?

**Comment by ralsina** [comment]
It's early and I have had no coffee yet, but read_metadata can raise any other exception, and then the exact same thing will happen, right? This would only fix one specific problem.

**Comment by pluser** [comment]
No. read_metadata() can raise other exception like RuntimeError, KeyError, NameError, or something, but If those were raised, Nikola show Traceback correctly. Only StopIteration make false report as far as I know.

**Comment by Kwpolska** [comment]
@ralsina, opinions?

**Comment by ralsina** [comment]
@Kwpolska I'll have to take a real look at the code that calls that. I suspect it's not a problem with every plugin but with task plugins because we are unrolling iterators, so StopIteration makes everyone go nuts.

**Pull request closed without merging**
