### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by Kwpolska**

### CODE REVIEW

**Comment by ralsina** [comment]
Should we update this with the fixed version? Maybe >=2.7.0 instead?

**Comment by Kwpolska** [comment]
did you mean `Yapsy>=1.11.123`?  test dependencies are flagged down at exact versions.

**Comment by ralsina** [comment]
I meant pytest, but if we have them on fixed numbers, that's ok for me.

Yapsy let's wait for the next minor release that will have the fix and a consistent version number...

**Comment by ralsina** [comment]
We could go back to 1.10.143 or something like that until the new release is out, that one works.

Or 1.11.123b :-P

**Pull request closed without merging**
