### PR TITLE
Fix #1689

### LINKED ISSUE #1689: Very-old-format-metadata breaks
The really-old-metadata (untagged lines in a meta file) crashes.

### PR DESCRIPTION
**Pull request by ralsina**
Doh

### CODE REVIEW

**Comment by Kwpolska** [comment]
The correct fix would be to remove `updated` from this list, because otherwise the labels won’t match up.  Applying that and merging.

cc @Aeyoun

**Comment by ralsina** [comment]
or put updated last and use 8?

**Comment by Kwpolska** [comment]
just upgrade to the new .meta format already

**Comment by ralsina** [comment]
May I point out that *we* had not upgraded for *our* site? :-)

**Comment by Kwpolska** [comment]
I’ll write a converter plugin tomorrow.

**Pull request closed without merging**
