### PR TITLE
WIP: Add locale handlers for month names and formatted dates.

### PR DESCRIPTION
**Pull request by felixfontein**
See #2029.

### CODE REVIEW

**Comment by felixfontein** [comment]
First try to implement the ideas sketched in #2029, not really tested yet though.

**Comment by felixfontein** [comment]
Now tested it, works fine!

**Comment by ralsina** [comment]
To keep API compatibility for plugins that may be calling it, could you keep utils.formatted_date that just wraps LocaleBorg.formatted_date?

**Comment by felixfontein** [comment]
`utils.formatted_date` wasn't there until two (or so) days ago. I moved it there when fixing something in the Atom feed renderer.

**Comment by felixfontein** [comment]
see https://github.com/getnikola/nikola/pull/2028/files#diff-cca99a67a7b16498786d42c7f2f89444R1735

**Comment by ralsina** [comment]
LGTM then

**Comment by felixfontein** [comment]
Good, I'll merge then. I think now `formatted_date` found a good place in `utils` :)

**Pull request merged**
