### PR TITLE
Update _WINDOWS_LOCALE_GUESSES

### LINKED ISSUE #2343: Complete _WINDOWS_LOCALE_GUESSES
Currently, `_WINDOWS_LOCALE_GUESSES` has only 20 of 30+ locales. It should be updated to try to equate it with `TRANSLATIONS`.

### PR DESCRIPTION
**Pull request by sukiletxe**
Fixes #2343

### CODE REVIEW

**Comment by sukiletxe** [comment]
This is ready for review. I couldn't include `eo` because Esperanto is not available in Windows. Also, `nb` couldnt be included (`Norwegian (Bokmål)` was not interpreted correctly, I don't know why), and I changed it to plain `Norwegian`. Other

**Comment by Kwpolska** [comment]
> (Norwegian (Bokmål) was not interpreted correctly, I don't know why)

Probably an encoding issue.

**Comment by Kwpolska** [comment]
Please add yourself to AUTHORS.txt and a note about this to CHANGES.txt.

**Comment by sukiletxe** [comment]
Done.

**Comment by Kwpolska** [comment]
Thanks for your contribution!

**Pull request merged**
