### PR TITLE
Compiler config deps

### PR DESCRIPTION
**Pull request by ralsina**
This should fix Issue #1523

### CODE REVIEW

**Comment by felixfontein** [comment]
I think ```post.add_dependency_uptodate``` is not used correctly here. It is more or less directly added (for lists, its elements are added) to doit's ```uptodate``` field, which expects lists of ```False```, ```True```, ```None```, callables, or strings (which are executed as shell commands) (see http://pydoit.org/dependencies.html#uptodate). I think ```tools.config_changed``` should be used here to (somehow) wrap the data added.

**Comment by ralsina** [comment]
These are all lists of strings, so is that ok?

**Comment by felixfontein** [comment]
I think doit will try to execute each string as a shell command, and use its return value to determine whether the task changed or not. That's not what you want, I think?

**Comment by ralsina** [comment]
Indeed.

**Comment by ralsina** [comment]
Just out of curiosity, is add_dependency_uptodate used anywhere so I can see how it's done there?

**Comment by felixfontein** [comment]
If you want to update if the list of strings changed (maybe you want to sort the list to avoid list reordering triggering rebuilds), use ```tools.config_changed({1: your_string_list}, 'some unique identifier for the plugin')``` or so.

**Comment by felixfontein** [comment]
I found an example in one of my (not yet published) plugins:

```post.add_dependency_uptodate(utils.config_changed({1: some_data}, 'nikola.plugins.path.to.comment.and.its.name:' + post.base_path), False, 'page')```

**Comment by ralsina** [comment]
ok, pushing now.

**Comment by ralsina** [comment]
The ID you say "unique"... that means unique in the context of that specific task, right? Not unique across all the tasks?

**Comment by felixfontein** [comment]
It should be unique over all posts and tasks, because it could happen that different tasks add something to the uptodate dependency of a post, and many posts are on one index/list/... page, and all those uptodate dependencies are put into the uptodate dependency on the generated index/list/...

I'd use a combination of the task/plugin/... name and the post's source path.

**Comment by ralsina** [comment]
Ugh again then.

**Comment by ralsina** [comment]
Last question: it has to be unique across the whole build **and stable from one build to another**?

**Comment by felixfontein** [comment]
Yes. (Of course, it should be stable iff the options it contains don't change.)
So if you want to force a rebuilt if a list of strings changes (but its order doesn't depend), sort the list, put it into a ```config_changed``` object and make its tag depend on the plugin and the post.

**Pull request merged**
