### PR TITLE
themes: add microformats tags for post authors

### PR DESCRIPTION
**Pull request by mardy**
Based on http://microformats.org/wiki/h-entry and
http://microformats.org/wiki/h-card

Signed-off-by: Alberto Mardegan <mardy@users.sourceforge.net>

### Pull Request Checklist

- [x] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [x] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [x] I tested my changes.

### Description

This adds microformat tags to the author data already present in post headers. I plan to add more data for each author, but that's not a trivial change so I'll prepare an issue describing a proposal.

### CODE REVIEW

**Comment by Kwpolska** [comment]
Do we really need more strange classes in our HTML? What tools actually use and benefit from those?

**Comment by mardy** [comment]
> Do we really need more strange classes in our HTML? What tools actually use and benefit from those?

It's the recommended standard by the indieweb, and given that Nikola already supports parts of it (the `h-entry`) it seems normal to continue on that road. If you are concerned about the proliferation of classes, then maybe we can probably remove the `vcard` and `fn` classes, given that they are coming from an [obsoleted version of microformats](http://microformats.org/wiki/hcard), and `author`, which comes from the [hentry](http://microformats.org/wiki/hentry).

**Comment by mardy** [comment]
For comparison, the in the `nikola/data/themes/base/templates/post.tmpl` both the current `h-entry` and the old `hentry` classes are supported.

**Comment by Kwpolska** [comment]
It does, but the question is, do we really need that? Do we need any of these? Show me some tools that actually care about these (in whichever of the [15 competing standards](https://xkcd.com/927/)) and that have a significant enough userbase.

**Comment by mardy** [comment]
> It does, but the question is, do we really need that? Do we need any of these?

Yes, if one wants to implement [webmentions](https://www.w3.org/TR/webmention/).

> Show me some tools that actually care about these (in whichever of the [15 competing standards](https://xkcd.com/927/)) and that have a significant enough userbase.

I honestly don't understand all this pushback on a trivial change that just improves web interoperability. If we go by the userbase logic, Nikola wouldn't have been written — everybody uses Facebook and Instagram, while a few geeks use Blogger and a handful of people use Wordpress :-)

The standard is there, but while even open-source projects push back on supporting it, it's just silly to expect to find a significant userbase for it. What I can tell you is that [support was added in Jekyll](https://github.com/jekyll/minima/pull/160) and that's why Jekyll has a [nice page in the IndieWeb wiki](https://indieweb.org/Jekyll) while Nikola is [not even listed](https://indieweb.org/static_site_generator). Improving microformats support is a very easy thing we can do with very little cost, and it can help us earn a strong support in the IndieWeb community; certainly it's not a "significant enough userbase", but it's a community with a rather high ratio of developers and otherwise technically skilled/aware bloggers: which seems to me the ideal community which would support Nikola's development.

**Comment by Kwpolska** [comment]
> I honestly don't understand all this pushback on a trivial change that just improves web interoperability.

No change is trivial. Trivial changes add up, and they need maintenance. We are not really invested in microformats, and it shows, because

> maybe we can probably remove the vcard and fn classes, given that they are coming from an obsoleted version of microformats, and author, which comes from the hentry.

(and no, `author` does not necessarily come from `hentry`, it comes from logical class names for items you may want to style in CSS)

> What I can tell you is that support was added in Jekyll and that's why Jekyll has a nice page in the IndieWeb wiki while Nikola is not even listed.

It’s a wiki, which means you can add Nikola to the list. Moot point.

**Comment by ralsina** [comment]
Merging. Let's err on the side of niceness and assume @mardy will maintain it since he's using it in his own site.

**Comment by mardy** [comment]
I'll certainly will! Thanks, Roberto!

**Pull request merged**
