### PR TITLE
updated readme with nikola architecture

### PR DESCRIPTION
**Pull request by khatribharat**
Updated `README.rst` with a section on Nikola Architecture

### CODE REVIEW

**Comment by ralsina** [comment]
Hey that's pretty nifty!

What did you use to edit it? We may have to change it in the future and it would be better to have the same tool.

Is there a way to layout the diagram so it's not so wide?

**Comment by khatribharat** [comment]
I used https://www.draw.io to create it. `nikola-architecture-draw-io.xml` can be imported and edited using `draw.io` for any changes in future.

**Comment by Kwpolska** [comment]
nikola auto ≠ doit auto. Just remove that tile.

The XML file contains your user agent, please clean it up. It would also be
better if you used SVG.
We'll have to host it on the website and link there so that pypi shows it
correctly; we should also put it in the internals documentation.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by felixfontein** [comment]
What kind of file format is this? (I know it's XML, but that is mainly a very thin wrapper around something which looks base64 encoded or so.) Can it be used with anything else but draw.io?

**Comment by schettino72** [comment]
nice...

- *nitpick*: please spell `doit` using only lower-case letters
- `commands` are also implementations of `doit` commands

@Kwpolska exactly because Nikola `auto` is different from doit `auto` it should be in diagram. It shows the commands that are overwritten by Nikola.

**Comment by khatribharat** [comment]
Does [this](https://github.com/khatribharat/nikola/blob/readme-update/nikola-architecture-draw-io.svg) look good?
@felixfontein I'm not sure if the format could be imported into other drawing tools or not. 
@ralsina I've not been able to change the layout, it certainly looks wide right now.

**Comment by khatribharat** [comment]
@Kwpolska Added SVG and JPG (since GitHub doesn't render SVG). Also cleaned up [nikola-architecture-draw-io.xml](https://github.com/khatribharat/nikola/blob/master/nikola-architecture-draw-io.xml)

**Comment by Kwpolska** [comment]
@khatribharat 
1. Remove the JPG, as JPG is the worst possible format for presenting images (as opposed to pictures).
2. Add a PNG.
3. Put all the files (svg, xml, png) in a different directory, like `docs/architecture`.
4. Then squash the commits so the repo is cleaner.

**Comment by khatribharat** [comment]
@Kwpolska Done as suggested.

**Comment by Kwpolska** [comment]
Perfect.  @ralsina, pull the trigger if it’s okay.

@khatribharat, one more thing (that can be done at any time, irregardless of merge status): add `bharat.k@directi.com` to your [GitHub emails](https://github.com/settings/emails).

**Comment by khatribharat** [comment]
@Kwpolska That's my office email, can't add that here. ;) Only some emails from my personal email address contain this as the alternate email in the signature.

**Comment by Kwpolska** [comment]
@khatribharat (And now it’s publicly available for anyone who clones our repo and cares to look at this commit.)

**Comment by khatribharat** [comment]
Thanks for the merge! My first contribution to a big open source project. :smiley:

**Pull request merged**
