### PR TITLE
Fixing #2347.

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes message inheritance as described in #2347.

### CODE REVIEW

**Comment by Kwpolska** [comment]
:+1: from me, @ralsina?

**Comment by Kwpolska** [comment]
I updated the changelog for this. Also, in the future, please make sure to use “fix” or any of the other [special closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in commit messages (fix{,es,ed}, close{,s,d}, resolve{s,d}) so that GitHub closes the issue when this is merged (I did that in my changelog commit)

**Comment by felixfontein** [comment]
Thanks for updating changelog! I keep forgetting that Github doesn't like "fixing" for that... Sorry :)

**Comment by ralsina** [comment]
LGTM

**Comment by ralsina** [comment]
Looks like we lost travis???? I see no test reports in this branch!

**Comment by Kwpolska** [comment]
GitHub doesn’t react well to `[ci skip]` in PRs, it seems. Merging on the basis of the first commit building properly.

**Pull request merged**
