### PR TITLE
Unify translation es

### PR DESCRIPTION
**Pull request by jjconti**
I did this in 2 separate commits because I'm not sure if you're agree with the second one.

### CODE REVIEW

**Comment by ralsina** [comment]
All the translation works done at transifex, please redo there, sorry!

**Comment by jjconti** [comment]
ok!

**Comment by jjconti** [comment]
Are you ok with both changes?

**Comment by jjconti** [comment]
I've just created my account. Can anyone add me to the Spanish team? @Kwpolska?

**Comment by ralsina** [comment]
You have to request it, AFAIK

**Comment by Kwpolska** [comment]
@jjconti: added on Transifex; please accept the invite, fix those two strings, and also the 6 missing strings.

**Comment by jjconti** [comment]
I added the missing ones, edited one, but I couldn't edit the other: https://www.transifex.com/ralsina/nikola/translate/#es/messages/11975695. It says I have not permission.

**Comment by Kwpolska** [comment]
On 4 September 2015 at 15:54, Juan José Conti <notifications@github.com>
wrote:

> I added the missing ones, edited one, but I couldn't edit the other:
> https://www.transifex.com/ralsina/nikola/translate/#es/messages/11975695.
> It says I have not permission.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getnikola/nikola/pull/2012#issuecomment-137743636>.
>

I did it for you, Transifex is a crazy place.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by jjconti** [comment]
Thanks.

**Comment by jjconti** [comment]
@Kwpolska this still need to be changed https://www.transifex.com/ralsina/nikola/translate/#es/messages/11975695

**Comment by ralsina** [comment]
The problem is I marked that one as reviewed, it seems.

**Pull request closed without merging**
