### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I translated zh_TW locale, please review and merge. :smiley:

### CODE REVIEW

**Comment by ralsina** [comment]
Sorry, but Nikola translations are actually handled via transifex. Can you redo it there?

https://www.transifex.com/ralsina/nikola/dashboard/

**Comment by s8321414** [comment]
Ah, seems it's already done, I will close this PR.

**Comment by s8321414** [comment]
I can see they are translated about one week ago :smiley:

**Comment by Kwpolska** [comment]
Translations in Nikola are usually updated right before release, but I'll
import those later today.

-- 
Chris Warrick <https://chriswarrick.com/>

**Pull request closed without merging**
