### PR TITLE
Issue #3291 - extra_footer block in base.tmpl

### PR DESCRIPTION
**Pull request by tdimitrov**
Add extra_footer block in bootstrap4/templates/base.tmpl

### Pull Request Checklist

- [x] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [ ] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [x] I tested my changes.

### CODE REVIEW

**Comment by Kwpolska** [comment]
We don’t have this for other parts of the page. We might want to add an `extra_` block to other places. Opinions? @ralsina?

**Comment by ralsina** [comment]
Don't see why not.

**Comment by tdimitrov** [comment]
I've pushed another commit, which adds the block to the rest of the mako templates.

**Comment by Kwpolska** [comment]
@gwax Jinja2 themes are auto-generated from the Mako themes.

**Comment by Kwpolska** [comment]
I added `extra_header` in commit c589a1b32.

**Pull request merged**
