### PR TITLE
Fix #2847 – non-fatal rev-parse failures in github_deploy

### LINKED ISSUE #2847: github_deploy shouldn’t fail if it can’t determine the source commit
[github_deploy](https://github.com/getnikola/nikola/blob/34e4767194c72c473ff4a31b9a8738f8cc6d662e/nikola/plugins/command/github_deploy.py#L128) tries to deploy from the branch specified by `GITHUB_SOURCE_BRANCH`, which [defaults](https://github.com/getnikola/nikola/blob/34e4767194c72c473ff4a31b9a8738f8cc6d662e/nikola/nikola.py#L620) to `master`. 

This doesn't make sense to me. The default behavior that I would expect would be to just deploy the current contents of the repo.

### PR DESCRIPTION
**Pull request by Kwpolska**
This is #2847. cc @asmeurer

*(note to future self: this goes to v7-maintenance as well)*

### CODE REVIEW

**Comment by asmeurer** [comment]
Does it not try to deploy from `master` even if `master` exists when `GITHUB_COMMIT_SOURCE = False`?

**Comment by Kwpolska** [comment]
It never did that. It only took the commit hash from there.

**Comment by asmeurer** [comment]
That wasn't what I saw when I was testing this on Travis. From my PR build it was apparently trying to build from master (the build failed because of a change that I had only made on my branch).

**Comment by Kwpolska** [comment]
Merged, it shouldn’t break much.

**Pull request merged**
