### PR TITLE
Refactor newpost (Fix #1943)

### LINKED ISSUE #1943: Nikola new_post -F works weird
Because of the selective plugin disabling it now misses a few formats when called with a conf.py

Plan:

- [ ] Keep the data about disabled compilers in the Nikola class
- [ ] Refactor new_post so all the standalone functions that always get the same arguments go away

### PR DESCRIPTION
**Pull request by ralsina**
There are some  minor changes, in that more plugins are not loaded, so for them friendlyName is not available.

### CODE REVIEW

**Comment by Kwpolska** [comment]
444-446 are old docs.

How does it look now, and could we patch in friendly names for the built-in compilers?

**Comment by ralsina** [comment]
@Kwpolska we'd have to put friendly names in the plugin metadata, which makes sense.

**Comment by Kwpolska** [comment]
Could you take care of this?



-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by ralsina** [comment]
@Kwpolska sure

**Pull request merged**
