### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by Kwpolska**

### CODE REVIEW

**Comment by Kwpolska** [comment]
Stupid computers.

DO NOT MERGE.

**Comment by Kwpolska** [comment]
mock==1.2.0, which undid the things that broke in 1.1.3, breaks some of our tests.  No way to write compatible code?  LOVELY.

Someone bored can fix it, or leave it be.

**Comment by ralsina** [comment]
So, the fixes for 1.1.4 break again in 1.2.0? I can check that later :-)

**Comment by ralsina** [comment]
To be honest, 1.2.0 seems broken to me:

```
-> meta_data = [x.strip() for x in meta_file.readlines()]
(Pdb) meta_file.readlines()
u'.. title: Nikola needs more tests!\n.. date: 2012/09/15 19:52:05\n.. tags:\n.. link:\n.. description:\n\nPost content\n'
(Pdb) meta_file.seek(0)
<MagicMock name='open().seek()' id='140399406068560'>
(Pdb) meta_file.read()
'.. title: Nikola needs more tests!\n.. date: 2012/09/15 19:52:05\n.. tags:\n.. link:\n.. description:\n\nPost content\n'
```

read() and readlines() return the same thing, and readlines() is not splitting in lines at all.

**Comment by Kwpolska** [comment]
Woah.  Mind [reporting upstream](https://github.com/testing-cabal/mock/issues)?

**Comment by ralsina** [comment]
https://github.com/testing-cabal/mock/issues/291

**Pull request closed without merging**
