### PR TITLE
Compiler config deps

### PR DESCRIPTION
**Pull request by ralsina**
Use add_dependency_uptodate correctly

### CODE REVIEW

**Comment by ralsina** [comment]
I think this way makes more sense. Comments appreciated :-)

**Comment by Kwpolska** [comment]
:+1: from me.

**Comment by felixfontein** [comment]
This still needs some packaging, like in a ```config_changed``` object. I'll add that.

**Comment by felixfontein** [comment]
Well, there are two things we could do:
  a) ask that only correct things are put into ```compiler.config_dependencies```;
  b) change ```compiler.config_dependencies``` into a set and ask for strings to be put into it, then ```post.uptodate()``` has to create a sorted list out of it and put it into a ```tools.config_changed``` object.

Which one do you prefer?

**Comment by ralsina** [comment]
Let's keep the complexity in one place, otherwise for each compiler we have to know all this stuff about why it has to be a set and why it has to have a unique ID, and how unique it has to be, etc.

I'd say the compiler just has a list of strings, then the post creates a config_changed up to its own requirements out of it.

I think this is better because while there is a chance 3rd parties will want to write a compiler plugin, noone outside the project is touching Post.

**Comment by felixfontein** [comment]
Sounds good to me. And if anyone needs to add something more complex than simply a string (or several of them), or if the data depends on the post as well, they can still use the more complicated mechanism.

**Comment by Kwpolska** [comment]
Without this, nikola is broken badly.  Merging.

**Comment by felixfontein** [comment]
It is indeed. But there was something missing for pandoc and markdown: the compilers also inserted a list of strings into the list (instead of strings). Merging that, too.

**Pull request merged**
