### PR TITLE
Use .rst as extension for all reStructured files we ship

### PR DESCRIPTION
**Pull request by ralsina**
I think I caught it all.

### CODE REVIEW

**Comment by Kwpolska** [comment]
Update the symlinks list please.

**Comment by ralsina** [comment]
@Kwpolska done

**Comment by Kwpolska** [comment]
AppVeyor still fails:

    error: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-66af395j-build\\docs\\sphinx\\creating-a-theme.rst'

**Comment by Kwpolska** [comment]
Did you forget to `git add` some files?

**Comment by ralsina** [comment]
I just fixed a conflict, will take a look again later (no more time)

**Comment by ralsina** [comment]
@Kwpolska seems to be just invariance now?

**Comment by Kwpolska** [comment]
AppVeyor still fails: https://ci.appveyor.com/project/Kwpolska/nikola/build/1.0.5982

**Comment by ralsina** [comment]
@Kwpolska I have no idea how that works on windows. The symlink is there...

**Comment by Kwpolska** [comment]
I can’t see it. https://github.com/getnikola/nikola/tree/use-rst-extension/docs/sphinx

**Comment by ralsina** [comment]
Ok, was not pushed. Let's see now.

**Pull request merged**
