### PR TITLE
Always including base post as dependency (#2956)

### LINKED ISSUE #2956: Posts not translated to DEFAULT_LANG cause Nikola to sometimes crash when the entire site is rebuilt
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.11

**Operating System:** Windows / Linux

### Description:

**Steps to reproduce**:
* `nikola init demo` (answer `en,es` to the language question, leave everything else as default)
* `cd demo`
* `nikola new_post -t test`
* Rename `test.rst` to `test.es.rst`
* `nikola build -a` (repeat preceded by `nikola clean` until it fails). Also works if using a CI to build (and if the `cache`, `output and `.doit*` are ignored or removed, as in my case).

### PR DESCRIPTION
**Pull request by felixfontein**
### Pull Request Checklist

- [X] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [X] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [X] I tested my changes.

### Description
Fixes #2956.

(`self.base_path` equals `cache/posts/test.es.html` in sample of #2956.)

### CODE REVIEW

**Comment by Kwpolska** [comment]
#3073 needs a more resilient solution.

```
% for i in $(seq 1 100); do nikola console -c "print(site.timeline[0].base_path)"; done
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.es.html
Scanning posts........done!
cache/posts/test.es.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.es.html
Scanning posts........done!
cache/posts/test.es.html
Scanning posts........done!
cache/posts/test.es.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.de.html
Scanning posts........done!
cache/posts/test.es.html
```

```
In [3]: site.timeline[0].deps('de')
Out[3]:
['cache/posts/test.de.html',
 'cache/posts/test.de.html',
 'posts/test.de.rst',
 'posts/test.de.rst']

In [4]: site.timeline[0].deps('en')
Out[4]: ['cache/posts/test.de.html', 'posts/test.de.rst']

In [5]: site.timeline[0].deps('es')
Out[5]:
['cache/posts/test.de.html',
 'cache/posts/test.es.html',
 'posts/test.de.rst',
 'posts/test.es.rst']
```

```
In [1]: site.timeline[0].deps('es')
Out[1]:
['cache/posts/test.es.html',
 'cache/posts/test.es.html',
 'posts/test.es.rst',
 'posts/test.es.rst']

In [2]: site.timeline[0].deps('de')
Out[2]:
['cache/posts/test.de.html',
 'cache/posts/test.es.html',
 'posts/test.de.rst',
 'posts/test.es.rst']

In [3]: site.timeline[0].deps('en')
Out[3]: ['cache/posts/test.es.html', 'posts/test.es.rst']

In [4]: site.timeline[0].deps('es')
Out[4]:
['cache/posts/test.es.html',
 'cache/posts/test.es.html',
 'posts/test.es.rst',
 'posts/test.es.rst']
```

**Comment by felixfontein** [comment]
Ok, this now also includes a fix for #3073. I also added a `sorted()` to avoid different file system enumeration orders causing rebuilds (`glob.glob()` makes no guarantees on the order of its result; see https://docs.python.org/3/library/glob.html).

**Comment by felixfontein** [comment]
@Kwpolska  I think the `sorted()` does that :)

**Comment by Kwpolska** [comment]
Yeah, that will do.

**Comment by felixfontein** [comment]
I guess we should also backport this to v7. (Should be straightforward, anyway.)

**Comment by Kwpolska** [comment]
Sure, will do tomorrow. Tomorrow is also when v8-beta will go out (after #3071 gets merged).

**Pull request merged**
