### PR TITLE
Fixes #2592

### LINKED ISSUE #2592: Archives (CREATE_MONTHLY_ARCHIVE = True) think all months are "None"
https://irclogs.getnikola.com/2015/

To reproduce locally: get https://github.com/getnikola/irclogs-site create any random files in `posts/*.rst`.

### PR DESCRIPTION
**Pull request by felixfontein**
Forgot one `return`...

### CODE REVIEW

**Comment by felixfontein** [comment]
@Kwpolska: the failing tests are the baseline. I don't see what went wrong here, though; maybe some dependency changed which now generates a slightly different output? Also, the same failing baseline differences show up for #2594, which has completely different code changes.

**Comment by Kwpolska** [comment]
That’s a lxml update, I just rebuilt the baseline.

**Comment by Kwpolska** [comment]
PS. small and obvious fixes do not need to be done through a pull request, you may commit to master directly.

**Comment by felixfontein** [comment]
Nope, that doesn't work anymore. I tried that first, and I got an error message that a review is required when trying to push to master. So I had to convert it to a PR first.

**Comment by Kwpolska** [comment]
Oh, that’s a side effect of requiring reviews and protecting branches. Which does not affect administrators, so I didn’t notice.

**Pull request merged**
