### PR TITLE
Pass positional arguments to template-based shortcodes

### PR DESCRIPTION
**Pull request by SpotlightKid**
Implements #2319. See rationale there.

Signed-off-by: Christopher Arndt <chris@chrisarndt.de>

### CODE REVIEW

**Comment by felixfontein** [comment]
The test failures are because Nikola couldn't download a gist. The changes LGTM and their tests don't fail.

**Comment by ralsina** [comment]
LGTM

**Comment by SpotlightKid** [comment]
Should I make a PR for `AUTHORS.txt`, `CHANGES.txt` and the docs as well?

**Comment by Kwpolska** [comment]
Go ahead.

**Pull request merged**
