### PR TITLE
New option FEED_PREVIEWIMAGE includes post previewimage meta

### PR DESCRIPTION
**Pull request by Aeyoun**
Issue #2095.

Checks to see if the previewimage is found in the content before including it. Avoids duplicate imagery. `<figure></figure>` is recommended [by Flipboard](https://about.flipboard.com/rss-spec/) and supported by Apple News and Feedly. There is very little we can do about optimizing here as every feed consumer recommends different file formats, sizes, markup, and whatnot.

* Deprecated RSS_PLAIN in favor of FEED_PLAIN for Atom and RSS
* Deprecated RSS_TEASERS in favor of FEED_TEASER for Atom and RSS

### CODE REVIEW

**Comment by Kwpolska** [comment]
What about RSS_READ_MORE_LINK?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
Also, why is this an option? We could probably just force it on everyone.
Most people won't mind.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Aeyoun** [comment]
> What about RSS_READ_MORE_LINK?

Considering removing it again. Last year, all the big sites were doing this. Now, no one is doing it anymore and I can’t figure out why they stopped.

> Also, why is this an option?

Some sites may include an `img` in their teasers already, depending on their site designs. Thought I’d give folks the options. Can flip the default to True, though.

**Comment by Kwpolska** [comment]
Let’s:

* leave both in
* default to `FEED_PREVIEWIMAGE = True`
* rename `RSS_READ_MORE_LINK` to `FEED_READ_MORE_LINK` and make sure it works in Atom, too

**Comment by Aeyoun** [comment]
It does work with Atom. I’ll rename and change defaults. See I set the wrong default for FEED_PLAIN too.

**Pull request merged**
