### PR TITLE
Fix for #3175: Use Markdown 3.0, fix some warnings

### PR DESCRIPTION
**Pull request by Tiefkuehlpizze**
### Pull Request Checklist

- [X] I’ve read the [guidelines for contributing](https://github.com/getnikola/nikola/blob/master/CONTRIBUTING.rst).
- [X] I updated AUTHORS.txt and CHANGES.txt (if the change is non-trivial) and documentation (if applicable).
- [X] I tested my changes.

### Description
Updated the the Markdown 3 branch and fixed the merge conflicts shown in #3175 to allow merging the original Pull request.

```
Ran 1 test in 0.641s

OK

Process finished with exit code 0
[2019-10-19T17:01:56Z] ERROR: Nikola: Unknown shortcode start (started at line 1, column 1)
```

Demosite is also working:
```(venv) $ python -m nikola init -qd demosite 
[2019-10-19T18:20:45Z] INFO: init: A new site with example data has been created at demosite.
[2019-10-19T18:20:45Z] INFO: init: See README.txt in that folder for more information.
```

I'm not sure if this error is relevant. The original tests in `test_shortcodes.py` didn't use `BaseTestCase` for some reason.
I hope this helps. I really appreciate the this project.

### CODE REVIEW

**Comment by Kwpolska** [comment]
What changes did you make to the `md3` branch, exactly? Is it just commit 6cbeb85901d5847bd3b227ce90a0b2c3fdd63993?

**Comment by Tiefkuehlpizze** [comment]
The original Pull Request hat had merge conflicts in the file `test_shortcodes.py`. The structure in the testcode was changed a bit so I tried to merge it and came to the result that the code on the branch is fine.
The single commit came from complaints from a check from Travis.

I'm fine, if you tell me, that this was unnecessary. But explain me then, how this merge conflict would be solved easier, please.

**Comment by Kwpolska** [comment]
Merge conflicts are usually solved by PR authors on our request, or by the maintainers when merging the PR. Making a PR that fixes merge conflicts in another PR is a bad idea, especially since GitHub didn’t do a great job displaying the history here, making it hard to tell what really happened in the PR.

> I'm not sure if this error is relevant. The original tests in test_shortcodes.py didn't use BaseTestCase for some reason.

BaseTestCase is not recommended for new tests, we moved to `pytest`-style tests instead of `unittest` class-based TestCases.

I fixed the merge conflict myself, and resolved it towards `pytest` testcases. The `md3` branch seems to pass CI now.

**Comment by Tiefkuehlpizze** [comment]
Okay. Thanks for explaining. I'm perfectly fine with that. :+1:

**Pull request closed without merging**
