### PR TITLE
ipynb in all themes

### PR DESCRIPTION
**Pull request by ralsina**
Enable mathjax for all ipynb posts/pages.

### CODE REVIEW

**Comment by Kwpolska** [comment]
:+1: for this bit, want to do the other half or can I take it?

**Comment by damianavila** [comment]
Seem OK to me...

**Comment by ralsina** [comment]
@Kwpolska feel free, I have a cold and code will be worse than usual for a couple of days :-P

**Comment by Kwpolska** [comment]
The other half is now up for review (c3d5a4e + ab8765e).

Also, ipython blogs often want a change in mathjax config (to accept the ugly `$e = mc^2$` syntax for math) — we still need that as setup for ipynb (unless you can always do `\(e = mc^2\)`)

**Comment by ralsina** [comment]
Looks good to me. +1

**Comment by damianavila** [comment]
I little bit late, but LGTM too...

**Pull request merged**
