### PR TITLE
Fix mangled pseudolinks (example patch for #2553)

### LINKED ISSUE #2553: url_replacer() mangles bare hash links
`<a href="#">something</a>` is mangled into `<a href="index.html">something</a>`, as is `<a href="#a">something</a>` unless there exists an element with `id="a"`. This causes a lot of problems for JavaScript-powered links. I have a simple example patch that fixes this.

### PR DESCRIPTION
**Pull request by pydsigner**
Simple patch to fix #2553.

### CODE REVIEW

**Comment by ralsina** [comment]
Optional before merging, can you add a line in CHANGES.txt? If you don't I'll do it.

**Comment by pydsigner** [comment]
@ralsina How does that look?

**Comment by ralsina** [comment]
@pydsigner awesome, merging.

**Comment by pydsigner** [comment]
Thanks much!

**Pull request merged**
