### PR TITLE
Flowr no jquery

### PR DESCRIPTION
**Pull request by ralsina**
This branch makes Flowr.js work without JQuery, and in the base theme. Therefore:

* The base gallery looks more like the bootstrap gallery
* All themes derived from base get a nicer gallery

I am hesitant to make the bootstrap theme use this, since it may break someone's derived theme.

### CODE REVIEW

**Comment by Kwpolska** [comment]
@ralsina flowr.js should be a symlink. Otherwise, it’s not kept up-to-date with Bower, and stuff like this happens.

**Comment by ralsina** [comment]
@Kwpolska updated from where? It's basically a fork at this point.

**Comment by Kwpolska** [comment]
Wait, so you hacked flowr not to require jQuery?

**Comment by ralsina** [comment]
Exactly :-)

**Comment by Kwpolska** [comment]
IMO it’d be better to focus on #2777 than use a stop-gap measure. But if you want this now, feel free to merge with no-reviews override.

**Comment by ralsina** [comment]
That's also happening soon, it's orthogonal. Merging, then.

**Pull request merged**
