### PR TITLE
Fix #3392

### LINKED ISSUE #3392: write_metadata removes content
When trying to use this new feature to make my old 2-post files single file, this happened.

image

### PR DESCRIPTION
**Pull request by ralsina**
Not really happy with this solution, opinion @Kwpolska ?

### CODE REVIEW

**Comment by ralsina** [comment]
> I’m also not sure about it, but I don’t think anything will be negatively affected by this change.

The alternative is to make the setter actually read the post source, change the setting, and re-write it correctly, which is quite scary.

**Comment by ralsina** [comment]
I am going to do the ambitious thing.

**Comment by ralsina** [comment]
I used this branch in my site to do this, and IT WORKED!

```python
two_post_files = [p for p in site.timeline if p.is_two_file]

for p in two_post_files:
    p.is_two_file = False
    print(p.title())
```

I no longer have any separate .meta files.

**Comment by Kwpolska** [comment]
I found one legitimate-ish use-case, the `pkgindex_scan` plugin updated is_two_file, because those are two-file posts, even though the other file is INI (`.plugin` or `.theme`) and not `.meta` (`pkgindex_compiler` can extract this as metadata). I updated `pkgindex_scan` to modify `_is_two_file` instead, and added a more appropriate split_metadata method to `pkgindex_compiler`.

**Comment by ralsina** [comment]
Oh, nice. I am guessing we may also need a separate function to determine the "second file path", really. Internally Nikola treats it like "the same as the post file + .meta"

**Comment by ralsina** [comment]
Well, as long as Nikola is the one extracting the metadata: yes.

BUT if the compiler plugin offers to extract it via supports_metadata, then
that takes precedence, I think?

**Pull request merged**
