### PR TITLE
fix for #1906

### PR DESCRIPTION
**Pull request by ralsina**
This is a proposed fix for #1906. I am not able to reproduce that at this moment, so I need someone who experiences it to check the fix (@Aeyoun maybe?)

### CODE REVIEW

**Comment by Aeyoun** [comment]
1. Reload once and reload again while it’s loading
2. touch posts/somefile.txt

Nikola wouldn’t rebuild anymore but will continue serving the same content until you restart auto. Not producing any messages about file events anymore. Will continue serving the browser and will display load messages as usual.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/events.py", line 322, in dispatch
    self.on_any_event(event)
  File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/command/auto/__init__.py", line 394, in on_any_event
    self.function(event)
  File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/command/auto/__init__.py", line 276, in do_refresh
    refresh_signal.send(path=p)
  File "/usr/local/lib/python3.4/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.4/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/command/auto/__init__.py", line 365, in notify
    self.send(response, response.is_binary)
  File "/usr/local/lib/python3.4/dist-packages/ws4py/websocket.py", line 265, in send
    self._write(data)
  File "/usr/local/lib/python3.4/dist-packages/ws4py/websocket.py", line 241, in _write
    raise RuntimeError("Cannot send on a terminated websocket")
RuntimeError: Cannot send on a terminated websocket

**Comment by Kwpolska** [comment]
On a side note, I was getting that broken pipe issue in the past. It was around that time when I implemented `nikola serve -d` and `nikola auto --no-server`.  Auto is really a weird thing.

**Comment by kerstin** [comment]
I see this was closed two years ago, but I'm getting this error _a lot_ when using `nikola auto`. However, it seems to only happen with Firefox. It annoyed me enough I decided to try it with Chrome and suddenly this problem is gone.

Chrome is not my default browser though, so I have to switch between more windows now.

Anyway, not sure if I should reopen/create a new issue/...

**Comment by kerstin** [comment]
Oops, just saw this wasn't actually an issue but a PR. (But, the log output included here is more similar to mine than the log messages in the linked issue.)

**Comment by Kwpolska** [comment]
`nikola auto` was overhauled recently as part of v8 work. Could you test the `master` branch from GitHub and check if you get any errors like that?

**Pull request merged**
