### PR TITLE
Support Latest posts

### PR DESCRIPTION
**Pull request by masayuko**
I would like to show a latest posts list on every post page.
Please consider this pull request.

### CODE REVIEW

**Comment by felixfontein** [comment]
You need to add dependencies of every post page with the last 10 posts (or at least some basic info about them). Also note that this will recompile *every* post page when you add a new post, which takes quite a long time for large blogs.

For that reason, the default number of posts should be 0 and not 10, as 0 will not cause this.

**Comment by Kwpolska** [comment]
No.

This is completely against Nikola’s principles.  If latest posts are displayed, you will basically kill all the benefits of automated rebuilds.

**Comment by schettino72** [comment]
What if you get parts of the page using AJAX? You could build this once and inject this in the page only in the client side when the page is displayed...

**Comment by Kwpolska** [comment]
You could easily achieve this by hand using the existing JSON for tag clouds, maybe with some code modifications.

**Comment by ralsina** [comment]
Or fetching RSS and displaying that using a widget.

**Comment by masayuko** [comment]
Thank you for reviewing my proposal.
I will consider another approach.

**Pull request closed without merging**
