### PR TITLE
Fix #1810 -- use watchdog in auto

### LINKED ISSUE #1810: Use watchdog in auto
Someone else suggested it a while ago, and I (wrongly) didn't even look at it. It would make auto more crossplatform, and simpler, at the cost of a changed dependency.

### PR DESCRIPTION
**Pull request by Kwpolska**
This is #1810.

Fixes (some of which would be useful even without `watchdog`):

* ~~make rebuilds actually work~~ cherry-picked onto master
* rebuild only once by using a set
* tell people we’re rebuilding and show them the log when we’re done

Also, we have to watch the directory with `conf.py` and filter out events because you must watch entire directories with `watchdog`.

cc @ralsina

### CODE REVIEW

**Comment by ralsina** [comment]
Yo mean rebuilds were not working?

**Comment by Kwpolska** [comment]
yeah, I broke them in f1e95ef211c8e3189bf5cab33351256956a79f91 and nobody really noticed…

**Comment by ralsina** [comment]
let's merge this then :)

**Comment by Kwpolska** [comment]
So is pyyaml no longer a huge problem?

**Comment by ralsina** [comment]
Well, at least cherrypick the fix? We can merge this later, then.

**Comment by Kwpolska** [comment]
done

**Comment by ralsina** [comment]
@Kwpolska let's merge this, dependencies be damned.

**Pull request merged**
