### PR TITLE
Fix getnikola/nikola-themes#49 -- https→http fallback

### PR DESCRIPTION
**Pull request by Kwpolska**
This is getnikola/nikola-themes#49.

cc @chacha92, @ralsina, @arusahni

Signed-off-by: Chris Warrick <kwpolska@gmail.com>

### CODE REVIEW

**Comment by ralsina** [comment]
I think before falling back to insecure HTTP, we should warn the user. Otherwise why bother with HTTPS in the first place?

**Comment by Kwpolska** [comment]
I’d just add `press ^C to abort` — some people just don’t care, and the security-conscious will race to their keyboard anyway.

**Comment by Kwpolska** [comment]
Even with `time.sleep(1)`. Makes sense?

**Comment by ralsina** [comment]
Sure, that's enough.

**Pull request merged**
